name: flutter_indocard_ocr_example
description: "Demonstrates how to use the flutter_indocard_ocr plugin."

publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_indocard_ocr:
    path: ../

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
